- name: Install desktop environment
  hosts: localhost
  tasks:
    - name: Install Packages
      ansible.builtin.package:
        name:
          - gdm3
          - i3
          - tmux
          - fzf
          - zsh
          - stow
          - firefox
        state: latest
    - name: change user shell to zsh
      become: yes
      user:
        name: "cla"
        shell: /bin/zsh
    - name: Download oh my zsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: ./install.sh
    - name: Delete current install
      become: yes
      become_user: cla
      file:
        state: absent
        path: ~/.oh-my-zsh
    - name: Install oh my zsh
      become: yes
      become_user: cla
      ansible.builtin.shell: bash ./install.sh
    - name: Delete extracted source directory
      file:
        state: absent
        path: ./install.sh
