- name: Install NeoVim
  hosts: localhost
  tasks:
    - name: Add neovim ppa
      ansible.builtin.command:
        argv:
          - add-apt-repository
          - ppa:neovim-ppa/stable
          - -y
    - name: Install Packages
      ansible.builtin.package:
        name:
          - neovim
        state: latest
